# Ejercicio 1

In [1]:
import pandas as pd
import numpy as np

ds_path = "../Datos/hawks.csv"

try:
    df = pd.read_csv(ds_path, encoding="cp1252", delimiter=";")
    pd.set_option('display.float_format', '{:.4f}'.format)
    print(f"✅ Dataset cargado exitosamente!")
    print(f"\n🔍 Primeras 5 filas:")
    display(df.head(5))
except Exception as e:
    print(f"❌ Error al cargar: {e}")

✅ Dataset cargado exitosamente!

🔍 Primeras 5 filas:

    Año Especie   Ala   Peso  Cola  Hallux
0  1994      RT  2770   9400   218     304
1  1997      RT  3730   9140   221     304
2  2000      RT  3790  10000   217     322
3  2000      RT  3920  11850   229     330
4  2002      RT  3650  11250   213     293

In [2]:
# Correlación entre Ala y Cola
corr = df["Ala"].corr(df["Cola"])
print("Correlación entre Ala y Cola:", corr)

Correlación entre Ala y Cola: 0.8998883674343948

In [3]:
# Estadisticas sin normalizar
q1 = df["Hallux"].quantile(0.25)
q3 = df["Hallux"].quantile(0.75)
iqr = q3 - q1
lower_whisker = q1 - 1.5 * iqr
upper_whisker = q3 + 1.5 * iqr
print("Estadisticas sin normalizar\n")
display(df["Hallux"].describe())
print("RIC:", iqr)
print("Bigote inferior:", lower_whisker)
print("Bigote superior:", upper_whisker)

# Estadisticas normalizadas
df["HalluxNorm"] = (df["Hallux"] - df["Hallux"].mean()) / df["Hallux"].std()
q1 = df["HalluxNorm"].quantile(0.25)
q3 = df["HalluxNorm"].quantile(0.75)
iqr = q3 - q1
lower_whisker = q1 - 1.5 * iqr
upper_whisker = q3 + 1.5 * iqr
print("\nEstadisticas normalizadas\n")
display(df["HalluxNorm"].describe())
print("RIC:", iqr)
print("Bigote inferior:", lower_whisker)
print("Bigote superior:", upper_whisker)

Estadisticas sin normalizar

count    893.0000
mean     291.7716
std      321.3240
min       95.0000
25%      152.0000
50%      295.0000
75%      315.0000
max     3414.0000
Name: Hallux, dtype: float64

RIC: 163.0
Bigote inferior: -92.5
Bigote superior: 559.5

Estadisticas normalizadas

count   893.0000
mean     -0.0000
std       1.0000
min      -0.6124
25%      -0.4350
50%       0.0100
75%       0.0723
max       9.7168
Name: HalluxNorm, dtype: float64

RIC: 0.5072760661228204
Bigote inferior: -1.1959003897549678
Bigote superior: 0.8332038747363136

# Ejercicio 2

In [4]:
ds_path = "../Datos/globos.csv"

try:
    df = pd.read_csv(ds_path)
    print(f"✅ Dataset cargado exitosamente!")
    print(f"\n🔍 Primeras 5 filas:")
    display(df.head(5))
except Exception as e:
    print(f"❌ Error al cargar: {e}")

✅ Dataset cargado exitosamente!

🔍 Primeras 5 filas:

      Color Tamanio Se_estira?    Edad Inflado?
0  Amarillo   Chico         Si  Adulto       Si
1  Amarillo   Chico         Si    Nene       Si
2  Amarillo   Chico         No  Adulto       No
3  Amarillo   Chico         No    Nene       No
4  Amarillo  Grande         Si  Adulto       Si

In [5]:
# Diccionarios de mapeo
map_color = {'Rojo': 1, 'Amarillo': 0}
map_estira = {'Si': 1, 'No': 0}
map_edad = {'Adulto': 1, 'Nene': 0}
map_tamanio = {'Chico': 0, 'Mediano': 0.5, 'Grande': 1}
map_inflado = {'Si': 1, 'No': 0}

# Aplicamos la conversión
df['Color'] = df['Color'].replace(map_color)
df['Se_estira?'] = df['Se_estira?'].replace(map_estira)
df['Edad'] = df['Edad'].replace(map_edad)
df['Tamanio'] = df['Tamanio'].replace(map_tamanio)
df['Inflado?'] = df['Inflado?'].replace(map_inflado)

print("\nDataFrame numerizado:")
display(df)

DataFrame numerizado:

C:\Users\gonza\AppData\Local\Temp\ipykernel_9540\3536557845.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Color'] = df['Color'].replace(map_color)
C:\Users\gonza\AppData\Local\Temp\ipykernel_9540\3536557845.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Se_estira?'] = df['Se_estira?'].replace(map_estira)
C:\Users\gonza\AppData\Local\Temp\ipykernel_9540\3536557845.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Edad'] = df['Edad'].replace(map_edad)
C:\Users\gonza\AppData\Local\Temp\ipykernel_9540\3536557845.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Tamanio'] = df['Tamanio'].replace(map_tamanio)
C:\Users\gonza\AppData\Local\Temp\ipykernel_9540\3536557845.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Inflado?'] = df['Inflado?'].replace(map_inflado)

    Color  Tamanio  Se_estira?  Edad  Inflado?
0       0   0.0000           1     1         1
1       0   0.0000           1     0         1
2       0   0.0000           0     1         0
3       0   0.0000           0     0         0
4       0   1.0000           1     1         1
5       0   1.0000           1     0         1
6       0   0.5000           0     1         0
7       0   0.5000           0     0         0
8       1   0.0000           1     1         1
9       1   0.0000           1     0         0
10      1   0.5000           0     1         0
11      1   0.5000           0     0         0
12      1   1.0000           1     1         1
13      1   1.0000           1     0         0
14      1   1.0000           0     1         0
15      1   1.0000           0     0         0

In [6]:
import sys
import os

# Ruta absoluta a la carpeta "Fuentes"
ruta_fuentes = os.path.abspath(os.path.join(os.getcwd(), "..", "Fuentes"))
sys.path.append(ruta_fuentes)

# Ahora podés importar
from ClassPerceptron import Perceptron

# Separar features y target
X = df[["Color","Tamanio","Se_estira?","Edad"]].astype(float).values
T = df["Inflado?"].astype(int).values  # 0 o 1

# Pesos y sesgo de los perceptrones
perceptrones = [
    [0.050, 0.006, -0.068, -0.047, 0.005],      # Perceptrón 1
    [-0.494, -0.003, 0.722, 0.489, -0.4943],    # Perceptrón 2
    [0.06, 0.004, 0.1278, 0.021, -0.1132],      # Perceptrón 3
    [0.296, 0.026, -0.576, -0.287, 0.371],      # Perceptrón 4
    [0.994, 0.006, -1.466, -0.989, 0.988]       # Perceptrón 5
]

# Evaluar cada perceptrón
peorAciertos = 100
p = Perceptron()
for i, p_vals in enumerate(perceptrones, start=1):
    p.w_ = np.array(p_vals[:4])
    p.b_ = p_vals[4]

    Y = p.predict(X)
    aciertos = np.sum(Y == T)
    if (aciertos == T.size):
        print("Perceptron", i, "clasifico los", aciertos, "correctamente")
    else:
        print("Perceptron", i, "solo clasifico", aciertos)
        if (aciertos < peorAciertos):
            peorAciertos = aciertos
            peorP = i

if (peorAciertos != 100):
    print("Perceptron", peorP, "fue el peor")

Perceptron 1 solo clasifico 4
Perceptron 2 clasifico los 16 correctamente
Perceptron 3 solo clasifico 14
Perceptron 4 solo clasifico 0
Perceptron 5 solo clasifico 1
Perceptron 4 fue el peor

# Ejercicio 3

In [7]:
# Funcion para normalizar edad
def normalizarEdad(edad, edadMin=53, edadMax=60):
    return (edad - edadMin) / (edadMax - edadMin)

# Creo e inicializo perceptron
p = Perceptron()
p.w_ = np.array([0.0807, 0.074])
p.b_ = -0.0742

# Creo los ejemplos a analizar
X = np.array([[normalizarEdad(50),0],[normalizarEdad(51),0.5],[normalizarEdad(54),1]])

# Resultados del perceptron
Y = p.predict(X)
for i, p_vals in enumerate(Y, start=1):
    if p_vals:
        print("El paciente", i, "necesita hacer el examen")
    else:
        print("El paciente", i, "no necesita hacer el examen")

El paciente 1 no necesita hacer el examen
El paciente 2 no necesita hacer el examen
El paciente 3 necesita hacer el examen

# Ejercicio 4

In [8]:
ds_path1 = "../Datos/drugs_train.csv"
ds_path2 = "../Datos/drugs_test.csv"

try:
    df_train = pd.read_csv(ds_path1)
    print(f"✅ Dataset cargado exitosamente!")
    print(f"\n🔍 Primeras 5 filas:")
    display(df_train.head(5))
    df_test = pd.read_csv(ds_path2)
    print(f"✅ Dataset cargado exitosamente!")
    print(f"\n🔍 Primeras 5 filas:")
    display(df_test.head(5))
except Exception as e:
    print(f"❌ Error al cargar: {e}")

✅ Dataset cargado exitosamente!

🔍 Primeras 5 filas:

   Age Sex    BP Cholesterol     Na      K   Drug
0   16   M   LOW        HIGH 0.7430 0.0619  drugC
1   42   F  HIGH        HIGH 0.5332 0.0253  drugY
2   33   F   LOW        HIGH 0.8584 0.0256  drugY
3   47   M   LOW        HIGH 0.6973 0.0689  drugC
4   56   F  HIGH        HIGH 0.7510 0.0296  drugY

✅ Dataset cargado exitosamente!

🔍 Primeras 5 filas:

   Age Sex      BP Cholesterol     Na      K   Drug
0   47   F     LOW        HIGH 0.5398 0.0536  drugC
1   49   M     LOW      NORMAL 0.6259 0.0568  drugX
2   50   M    HIGH        HIGH 0.5183 0.0692  drugA
3   32   F  NORMAL        HIGH 0.5494 0.0735  drugX
4   40   M    HIGH        HIGH 0.5571 0.0200  drugY

### Numerizo

In [9]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

le = LabelEncoder()
ohe = OneHotEncoder(sparse_output=False, dtype=int)

mapaBP = {"LOW": 0, "NORMAL": 1, "HIGH": 2}
mapaC = {"NORMAL": 0, "HIGH": 1}

def numerizar(df):
    try:
        df["Sex"] = le.fit_transform(df['Sex'])
        df["BP"] = df["BP"].replace(mapaBP)
        df["Cholesterol"] = df["Cholesterol"].replace(mapaC)
        
        #onehot = ohe.fit_transform(df[["Sex", "BP", "Cholesterol"]])
        #onehot_df = pd.DataFrame(onehot, columns=ohe.get_feature_names_out(["Sex", "BP", "Cholesterol"]))
        #df[onehot_df.columns] = onehot_df
        
        df["Drug"] = (df["Drug"] == "drugY").astype(int)
    except KeyError:
        None
    return df

df_train = numerizar(df_train)
df_test = numerizar(df_test)

display(df_train.head())
display(df_test.head())

C:\Users\gonza\AppData\Local\Temp\ipykernel_9540\391523101.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["BP"] = df["BP"].replace(mapaBP)
C:\Users\gonza\AppData\Local\Temp\ipykernel_9540\391523101.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Cholesterol"] = df["Cholesterol"].replace(mapaC)
C:\Users\gonza\AppData\Local\Temp\ipykernel_9540\391523101.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["BP"] = df["BP"].replace(mapaBP)
C:\Users\gonza\AppData\Local\Temp\ipykernel_9540\391523101.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Cholesterol"] = df["Cholesterol"].replace(mapaC)

   Age  Sex  BP  Cholesterol     Na      K  Drug
0   16    1   0            1 0.7430 0.0619     0
1   42    0   2            1 0.5332 0.0253     1
2   33    0   0            1 0.8584 0.0256     1
3   47    1   0            1 0.6973 0.0689     0
4   56    0   2            1 0.7510 0.0296     1

   Age  Sex  BP  Cholesterol     Na      K  Drug
0   47    0   0            1 0.5398 0.0536     0
1   49    1   0            0 0.6259 0.0568     0
2   50    1   2            1 0.5183 0.0692     0
3   32    0   1            1 0.5494 0.0735     0
4   40    1   2            1 0.5571 0.0200     1

### Sin normalizar

In [10]:
ppn = Perceptron(alpha=0.1, n_iter=30)

np.set_printoptions(suppress=True, precision=4)

X = df_train.drop(columns=["Drug"]).to_numpy()
T = df_train["Drug"].to_numpy()

ppn.fit(X,T)

X = df_test.drop(columns=["Drug"]).to_numpy()
T = df_test["Drug"].to_numpy()

Y = ppn.predict(X)
aciertos = np.sum(Y == T)

if (aciertos == T.size):
    print("Clasifico todo correctamente")
else:
    print("Solo clasifico",aciertos,"de",T.size)

Solo clasifico 18 de 40

### Normalizacion lineal

In [15]:
def normLineal(df):
    df["Age"] = (df['Age']-df['Age'].min())/(df['Age'].max()-df['Age'].min())
    df["Sex"] = (df['Sex']-df['Sex'].min())/(df['Sex'].max()-df['Sex'].min())
    df["BP"] = (df['BP']-df['BP'].min())/(df['BP'].max()-df['BP'].min())
    df["Cholesterol"] = (df['Cholesterol']-df['Cholesterol'].min())/(df['Cholesterol'].max()-df['Cholesterol'].min())
    df["Na"] = (df['Na']-df['Na'].min())/(df['Na'].max()-df['Na'].min())
    df["K"] = (df['K']-df['K'].min())/(df['K'].max()-df['K'].min())

ppn = Perceptron(alpha=0.1, n_iter=30)

df_train_l = df_train.copy()
df_test_l = df_train.copy()

normLineal(df_train_l)
normLineal(df_test_l)

X = df_train_l.drop(columns=["Drug"]).to_numpy()
T = df_train_l["Drug"].to_numpy()

ppn.fit(X,T)

X = df_test_l.drop(columns=["Drug"]).to_numpy()
T = df_test_l["Drug"].to_numpy()

Y = ppn.predict(X)
aciertos = np.sum(Y == T)

if (aciertos == T.size):
    print("Clasifico todo correctamente")
else:
    print("Solo clasifico",aciertos,"de",T.size)

Clasifico todo correctamente

### Normalizacion estandar

In [19]:
def normEstandar(df):
    df["Age"] = (df['Age']-df['Age'].mean())/(df['Age'].std())
    df["Sex"] = (df['Sex']-df['Sex'].mean())/(df['Sex'].std())
    df["BP"] = (df['BP']-df['BP'].mean())/(df['BP'].std())
    df["Cholesterol"] = (df['Cholesterol']-df['Cholesterol'].mean())/(df['Cholesterol'].std())
    df["Na"] = (df['Na']-df['Na'].mean())/(df['Na'].std())
    df["K"] = (df['K']-df['K'].mean())/(df['K'].std())

ppn = Perceptron(alpha=0.1, n_iter=30)

df_train_e = df_train.copy()
df_test_e = df_train.copy()

normEstandar(df_train_e)
normEstandar(df_test_e)

X = df_train_l.drop(columns=["Drug"]).to_numpy()
T = df_train_l["Drug"].to_numpy()

ppn.fit(X,T)

X = df_test_l.drop(columns=["Drug"]).to_numpy()
T = df_test_l["Drug"].to_numpy()

Y = ppn.predict(X)
aciertos = np.sum(Y == T)

if (aciertos == T.size):
    print("Clasifico todo correctamente")
else:
    print("Solo clasifico",aciertos,"de",T.size)

Clasifico todo correctamente